version: '3'
services:
  simple-producer-app-container:
    image: simple-producer-app:latest
    ports:
      - "8081:8081"
    networks:
      - producer-consumer-network

  simple-consumer-app-container:
    image: simple-consumer-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - simple-producer-app-container
    networks:
      - producer-consumer-network

networks:
  producer-consumer-network: